<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Entities\CargaVagones\**" />
    <EmbeddedResource Remove="Entities\CargaVagones\**" />
    <None Remove="Entities\CargaVagones\**" />
  </ItemGroup>
</Project>
